### ISSUE TITLE
Discrepancies between the latest data XML and the XSD schema

### ISSUE THREAD

**Issue by thomas-roberts316** [swandle06/AopXml#3]
We have encountered an issue where there seems to be a discrepancy between the current XSD and the latest AOP Wiki data. The issue we are facing is with:

`<xs:simpleType name="confidence-level-type">`

Which defines 4 options:

`<xs:restriction base="xs:string">
    <xs:enumeration value="Strong" />
    <xs:enumeration value="Moderate" />
    <xs:enumeration value="Weak" />
    <xs:enumeration value="not specified" />
</xs:restriction>
`

However in the latest data the values that are used are "High", "Moderate", "Low" and "Not specified".

There is also a `<oecd-project>` tag present in the data which is not in the schema.

The latest dataset also fails validation against the current.xsd in other areas, however these aren't causing us any issues yet. Please see this file file for the full output of the validation: [log.txt](https://github.com/swandle06/AopXml/files/6607424/log.txt)

The dataset we are using is aop-wiki-xml-2021-04-01.xml, and the schema is the latest available [here](https://aopwiki.org/info_pages/5) at the time of writing.

**Comment by swandle06** [comment]
The XML schema has been updated and errors with the XML export on the AOP-Wiki have been fixed. The current schema is available here: https://github.com/swandle06/AopXml/releases/tag/v1.0.1. At this stage, validation failures appear to be limited to a handful of controlled terms that are currently under review. Once those terms have been finalized, the schema will be updated accordingly.

This change is immediate when accessing the dynamic XML for individual AOPs (e.g.  https://aopwiki.org/aops/69.xml). The nightly download file (https://aopwiki.org/downloads/aop-wiki-xml.gz) will be correct as of tomorrow (5/8/2022). It will also be corrected in our next quarterly release on July 1, 2022. We do not correct errors in previous permanent downloads.
