### ISSUE TITLE
Add Release 2.6 properties

### ISSUE THREAD

**Issue by gingin77** [swandle06/AopXml#7]
See: https://github.com/swandle06/aopwiki/issues/243

**Comment by gingin77** [comment]
@swandle06 I tried to add coaches based on the pattern I saw for `aop-stressors`, but I don't know how to test the change or what would be the best patten to use for the other properties that should be added. Do you want to take this issue?

**Comment by swandle06** [comment]
Fixed this along with the 2.7 release items.
